version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres-template-api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: template_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-template-api:/var/lib/postgresql/data

volumes:
  postgres-template-api:
  