version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres-multitenant-api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: multitenant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-multitenant-api:/var/lib/postgresql/data

volumes:
  postgres-multitenant-api:
  